### ISSUE TITLE
possible to update `nix` version?

### ISSUE THREAD

**Issue by RatanRSur** [summa-tx/bitcoins-rs#108]
AFAICT, this package is the one preventing `nix` from being upgraded. Is it possible to update the `nix` version?

<img width="937" alt="Screenshot 2023-02-08 at 11 04 14 PM" src="https://user-images.githubusercontent.com/4733314/217715030-1de6c341-0abf-447c-a120-a8cd005cf0b3.png">

**Comment by prestwich** [comment]
released coins-ledger@0.7.1 with a dep on nix 0.26
