### ISSUE TITLE
support wordlist in other languages

### ISSUE THREAD

**Issue by 0xYYY** [summa-tx/bitcoins-rs#118]
add additional support for wordlist in other languages specified in [bip-0039](https://github.com/bitcoin/bips/tree/master/bip-0039)

this will enable usecases like the one mentioned in this [foundry issue](https://github.com/foundry-rs/foundry/issues/4560)

**Comment by 0xYYY** [comment]
will be happy to work on this one

**Comment by prestwich** [comment]
Ah please do. I recently refactored Bip39, so that should make it easier :)
