### ISSUE TITLE
Remove bitcoin-spv dependency

### ISSUE THREAD

**Issue by prestwich** [summa-tx/bitcoins-rs#36]
add sha256, hash256, rmd160, and hash160 utils to `core`

differentiate the `Hash256Digest` type to be hash-function specific (newtype-wrapped `[u8;32]`)

**Comment by prestwich** [comment]
@tynes do you think a `primitives` crate for this sort of thing is worth having?

**Comment by tynes** [comment]
Would `bitcoin-spv` depend on the crate too? If its going to be used in 2+ places, then possibly yes

**Comment by prestwich** [comment]
The only remaining dependency is `RawHeader`

**Comment by tynes** [comment]
It looks like the provider depends pretty heavily on the `RawHeader`. It feels like removing the dep would be implementing the bare minimal necessary to still make the provider work. Wdyt?

**Comment by prestwich** [comment]
Definitely agree. there's still the question of whether to break these out into a `core-types` crate tho
