### ISSUE TITLE
Prevent instantiation of txns with 0 inputs or outputs

### ISSUE THREAD

**Issue by prestwich** [summa-tx/bitcoins-rs#60]
Syntacitcally invalid transactions can be constructed. E.g. those with 0 inputs. This should be disabled

Should we update the transaction trait to `new -> Result<Self, Self::Error>` ?

**Comment by tynes** [comment]
`the size for values of type 'Self' cannot be known at compile time: doesn't have a size known at compile time`

**Comment by prestwich** [comment]
ya, to return Self in a trait you have to add a `where Self: Sized` constraint
