### ISSUE TITLE
Standardize on traits from RustCrypto

### ISSUE THREAD

**Issue by prestwich** [summa-tx/bitcoins-rs#69]
- Digest for Hashers from https://docs.rs/rust-crypto/0.2.36/crypto/digest/trait.Digest.html
- Signer/Verifier from https://docs.rs/signature/1.2.2/signature/

**Comment by tynes** [comment]
Does this also involve writing the backend for https://crates.io/crates/p256?

**Comment by prestwich** [comment]
No, we need to use k256 in coins-bip32 once it has an rfc6979 implementation

**Comment by prestwich** [comment]
Currently we're doing `pub struct DigestName([u8; 32])` and I think we should consider switching the internal type to GenericArray so that we can directly wrap the output of the RustCrypto hashers

**Comment by prestwich** [comment]
This is done for the hashes (now rely on `Digest`)

**Comment by tynes** [comment]
> Signer/Verifier from https://docs.rs/signature/1.2.2/signature/

So we would want to implement both of these for the `Secp256k1Backend` such that it is:
`pub trait Secp256k1Backend: Clone + std::fmt::Debug + PartialEq + signature::Signer + signature::Verifier`
https://github.com/summa-tx/bitcoins-rs/blob/44f68c6a40dbaf9dfe4c84182c107e6bc749bf1f/bip32/src/curve/model.rs#L99

`Secp256k1Backend.sign` would need to be updated to no longer take the private key. Big API change?
`Secp256k1Backend.verify` would also need to be updated to no longer take the public key.

`signature::Signer` is abstract over things that implement `signature::Signature`

The `coins_bip32::Signature` type is defined as an alias based on the backend.
https://github.com/summa-tx/bitcoins-rs/blob/44f68c6a40dbaf9dfe4c84182c107e6bc749bf1f/bip32/src/curve/libsecp.rs#L95-L96
https://github.com/summa-tx/bitcoins-rs/blob/44f68c6a40dbaf9dfe4c84182c107e6bc749bf1f/bip32/src/curve/rust_secp.rs#L108-L109

We would probably want to add a constraint to the `Secp256k1Backend` trait so its:
`type Signature: SigSerialize + signature::Signature`

https://github.com/summa-tx/bitcoins-rs/blob/44f68c6a40dbaf9dfe4c84182c107e6bc749bf1f/bip32/src/curve/model.rs#L109

Link to `Signature` type from `rust-libsecp256k1`: https://github.com/rust-bitcoin/rust-secp256k1/blob/b2e315f15447b1d11bfceb7632e7787cc2536036/secp256k1-sys/src/lib.rs#L119
Its not obvious to me how this would interact with the requirement that things implementing `signature::Signature` must be a "bag of bytes" (the `AsRef<[u8]>` bound)

**Comment by prestwich** [comment]
closed as of 8ed0d5a

I ended up just completely abandoning the swappable backends for ECDSA. It was more trouble than it was worth
