### ISSUE TITLE
Think about macros around core/src/hashes

### ISSUE THREAD

**Issue by tynes** [summa-tx/bitcoins-rs#70]
There is a lot of copy/paste code between `hash256.rs`, `blake2b256.rs` and `sha3_256.rs` (handshake branch, https://github.com/summa-tx/bitcoins-rs/pull/43/files#diff-4a068cf29f566ee9c1fee95ad83ee1f0). This could likely turn into a macro, it needs part of:
https://github.com/summa-tx/bitcoins-rs/blob/53a107c3002e1a3cb1375b46ef9024cbdc6c6624/core/src/macros.rs#L191

Maybe turn the part of the macro that implements `ByteFormat` into another macro, `impl_32_byte_format`, that can be also called on its own as well as inside of `mark_32_byte_hash`?
https://github.com/summa-tx/bitcoins-rs/blob/53a107c3002e1a3cb1375b46ef9024cbdc6c6624/core/src/macros.rs#L224

**Comment by prestwich** [comment]
okay. This is much improved in the refactor/new-hashes branch, which is based on the handshakes branch
