### ISSUE TITLE
Improve ByteFormat interface

### ISSUE THREAD

**Issue by prestwich** [summa-tx/bitcoins-rs#76]
`read_from` has a second argument that is unused in most cases. It only gets used when we're reading a sequence like `Vec<T>::read_from(source, 5)`. Instead, we should drop this method, avoid implementing implement something like `T::read_sequence(5)`

We should consider splitting up ByteFormat into an `Encode` and a `Decode` trait. Maybe consider re-using nomic's work. https://docs.rs/ed/0.1.5/ed/

**Comment by prestwich** [comment]
I've implemented `read_seq_from` and `write_seq_to` as well as moved many of the convenience functions outside the trait

**Comment by tynes** [comment]
> We should consider splitting up ByteFormat into an Encode and a Decode trait.

I feel like its more of an edge case when implementing only one of `Encode` or `Decode` is desired, but breaking them up does seem like what many other projects are doing (serde, borsh, ed)
