### ISSUE TITLE
rethink bitcoins-wasm

### ISSUE THREAD

**Issue by prestwich** [summa-tx/bitcoins-rs#78]
Bitcoins has undergone significant updates since I made this. Plus I've learned a bunch about wasm wrapping things. It would be relatively easy to restart.

- [ ] disable CI in `build.sh`
- [ ] redesign macros
- [ ] redo all exports
- [ ] fix the docs

This is not a blocker for initial release, I think

**Comment by tynes** [comment]
`bitcoins-wasm` doesn't currently build on `master`

**Comment by prestwich** [comment]
Yes, this is somewhat intentional. considering for deletion 🤔
