### ISSUE TITLE
Release a new patch version

### ISSUE THREAD

**Issue by sebastinez** [summa-tx/bitcoins-rs#89]
Hi folks,

Great work you're doing here :+1:
Wanted to ask if it would be possible to create a patch version to include the commit bb8c4fa and publish it to crates.io, to allow `ethers-rs` to update, since there are Ledgers Nano S and Nano X (like mine) that respond with a `APDU Response error Code 9000 ([APDU_CODE_NOERROR])` before that commit.

Thanks!

**Comment by prestwich** [comment]
tagged and published v0.4.2 thank you 🙌
